### ISSUE TITLE
推荐再添加一个stun服务器

### ISSUE THREAD

**Issue by vibbow** [HMBSbige/NatTypeTester#1]
stun.newrocktech.com
这是讯时在生产系统上用的stun服务器地址，可以保证稳定稳定使用。

比较奇怪的是，同样的网络
stun.newtocktech.com 测试出来的NAT类型是 RestrictedCone
stun.miwifi.com 测试出来的NAT类型是 PortRestrictedCone
不知道是什么原因

**Comment by HMBSbige** [comment]
这地址感觉不行啊，我 FullCone 的偶尔几次测出来是 RestrictedCone

**Comment by vibbow** [comment]
哈，这年头还有 FullCone 的存在？是做了 DMZ 映射了么...

**Comment by HMBSbige** [comment]
> 哈，这年头还有 FullCone 的存在？是做了 DMZ 映射了么...

是啊
![image](https://user-images.githubusercontent.com/19153265/62104254-a9e86700-b2d1-11e9-926f-0cda49e65693.png)

![image](https://user-images.githubusercontent.com/19153265/62104304-c84e6280-b2d1-11e9-9907-1feb01c9c728.png)

经测试，同一个端口第二次测就会成功测出 FullCone，第一次总是 RestrictedCone，我感觉是服务器的锅

**Comment by vibbow** [comment]
这没问题啊，你用其他stun服务器测试，只要路由器上的masquerade记录没消失，第二次测试就应该是FullCone的

**Comment by HMBSbige** [comment]
> 这没问题啊，你用其他stun服务器测试，只要路由器上的masquerade记录没消失，第二次测试就应该是FullCone的

其他服务器第一次都是能正常测出 FullCone 的...

**Comment by vibbow** [comment]
我看了一下路由器防火墙记录，是比较奇怪

做了DMZ映射的情况下

用 stun.miwifi.com 测试，只会产生一条连接
local ip:local port -> remote ip:3478

用stun.newrocktech.com 测试，会产生两条连接
local ip:local port -> remote ip:3478
local ip:local port -> remote ip:3479

**Comment by HMBSbige** [comment]
而且把防火墙开了后，stun.newtocktech.com 测出来的是 RestrictedCone，其他所有 stun 服务器测出来的是 PortRestrictedCone..

**Comment by HMBSbige** [comment]
我感觉这服务器还是有点问题

**Comment by vibbow** [comment]
搜了一下，好像做voip的stun服务器会用到3479
讯时, bbm, 3cx 都有用到3479

**Comment by vibbow** [comment]
可能是讯时的实现有一些问题把

**Comment by HMBSbige** [comment]
主要还是测试结果跟其他的都不一样

**Comment by HMBSbige** [comment]
😂 经测试讯时这个服务器是单 IP 服务器不能用来测试 NAT type，只能用来 Binding
