### ISSUE TITLE
建议取消占位字符

### ISSUE THREAD

**Issue by SekiBetu** [HMBSbige/NatTypeTester#11]
或者增加中间过程的占位符以让使用者知道测试过程还未结束

如下图，因为测试过程一些步骤的速度较慢，让使用者误以为Unknown为最终结果
![image](https://user-images.githubusercontent.com/38283893/104163471-62369c00-53ee-11eb-8786-ef4b7d82251b.png)

**Comment by HMBSbige** [comment]
¿ 我寻思结没结束难道不是看按钮是否可以用吗
