### ISSUE TITLE
ipv4/ipv6双栈网络问题

### ISSUE THREAD

**Issue by lns103** [HMBSbige/NatTypeTester#188]
stun.stunprotocol.org 有A和AAAA解析，同时支持ipv4和ipv6的nat测试，在纯v4网络下可以用该软件正常测试，在v4/v6双栈网络下，默认的监听0.0.0.0会测试失败，手动改为[::]之后可以测试v6 nat。
双栈网络下更换只有A记录的stun服务器可以正常测试v4 nat。

希望作者能够修复这个bug，另外提个建议，希望增加一个切换ipv4/ipv6的选项，不然很多小白就可能不知道如何测试v6 nat，或者在STUN服务器支持的情况下，同时对v4和v6进行测试

**Comment by HMBSbige** [comment]
1. 不认为是 bug，最多算设计不完美
2. 一般人的 IPv6 是不会有 NAT 的

**Comment by lns103** [comment]
> 1. 不认为是 bug，最多算设计不完美
> 2. 一般人的 IPv6 是不会有 NAT 的

但是部分v6网络存在防火墙（例如移动的流量，以及部分路由设备存在v6防火墙
所以v6测试还是存在意义的
![image](https://user-images.githubusercontent.com/49310852/168279294-f7d47402-8b23-46dc-919a-a992eb8e0007.png)
![image](https://user-images.githubusercontent.com/49310852/168279242-b6cacdb7-d676-4d17-b16f-93998d36b34d.png)

![image](https://user-images.githubusercontent.com/49310852/168279758-60fcb4b4-6ce7-4c69-abc6-d2e5f84072fc.png)
![image](https://user-images.githubusercontent.com/49310852/168279819-10228c09-2779-4fd8-976c-1cc2e41f6775.png)
