### ISSUE TITLE
同一个Local end重复点Test测试，NAT type会显示成FullCone

### ISSUE THREAD

**Issue by gba626** [HMBSbige/NatTypeTester#197]
在类型为PortRestrictedCone NAT3的网络下，第一次测试NAT type是PortRestrictedCone，第二次就变成FullCone了，之后只要不变换Local end就会一直是FullCone。但是手动更改Local end端口NAT type就又变回PortRestrictedCone了，也许可以添加一个Local end端口会自动变化的功能

**Comment by gba626** [comment]
我发现1.2以前是可以自动变化的，好像1.3允许自定义 Local end后就无法自动变化了，删除这个功能是有什么考量吗

**Comment by HMBSbige** [comment]
Duplicate of #4 #139
