### ISSUE TITLE
腾讯云这种弹性网卡应该用这个绑定，建议加上README后面

### ISSUE THREAD

**Issue by cnSchwarzer** [HMBSbige/NatTypeTester#199]
sudo docker run -d --restart=always --net=host --name=stunserver hmbsbige/stunserver --mode full --primaryadvertise 1.13.0.219 --altadvertise 146.56.194.158

**Comment by HMBSbige** [comment]
?

**Comment by cnSchwarzer** [comment]
> ?

就是有的云服务器不是你readme末尾那样起的，得指定advertise的ip而不是interface的ip

**Comment by HMBSbige** [comment]
不是本 repo 的主要主题，还有一堆参数和用法可以自行探索
