### ISSUE TITLE
貌似检测不是很准

### ISSUE THREAD

**Issue by magiclu** [HMBSbige/NatTypeTester#2]
![image](https://user-images.githubusercontent.com/3338197/63665284-46ccf000-c7fd-11e9-9c19-4651ddd93742.png)
![image](https://user-images.githubusercontent.com/3338197/63665362-93183000-c7fd-11e9-85ec-e45059cd71f2.png)
![image](https://user-images.githubusercontent.com/3338197/63665441-f73af400-c7fd-11e9-9609-32998814cfb8.png)
![image](https://user-images.githubusercontent.com/3338197/63665522-454ff780-c7fe-11e9-8f60-57da940c2172.png)

不同的服务器，nat显示不一样，多测几次也这样，防火墙开关都这样
有没有办法把微软的xbox检测的服务器加上？
win10自带的xbox软件nat检测貌似挺准的，就是要检测半天

**Comment by HMBSbige** [comment]
不准是因为你和服务器之间网络的问题，国内连国外服务器还有墙的问题，你填个错误的服务器地址还会返回 `UdpBlocked` 呢

不知道 xbox 的 STUN 服务器是什么 :D
