### ISSUE TITLE
各种错误

### ISSUE THREAD

**Issue by he852100** [HMBSbige/NatTypeTester#216]
![屏幕截图 2023-09-19 011610](https://github.com/HMBSbige/NatTypeTester/assets/26913892/7cc6a26e-8f0d-4ecb-90f4-0897f908f50d)
![屏幕截图 2023-09-19 011639](https://github.com/HMBSbige/NatTypeTester/assets/26913892/2cad7f0a-2667-498e-9bc1-70ba07cfeca3)
![屏幕截图 2023-09-19 011728](https://github.com/HMBSbige/NatTypeTester/assets/26913892/093c3f9c-38e6-4172-bf84-4845528abcb8)
![屏幕截图 2023-09-19 012153](https://github.com/HMBSbige/NatTypeTester/assets/26913892/0f7a6800-b602-4dc3-9d55-e929658c532b)

**Comment by he852100** [comment]
而且这么多版本，没有一个能记住代理设置的

**Comment by HMBSbige** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by HMBSbige** [comment]
有问题的是你
