### ISSUE TITLE
8.0.0应用默认缩放存在问题

### ISSUE THREAD

**Issue by liyuhaolol** [HMBSbige/NatTypeTester#219]
本人显示器屏幕为27寸4k，缩放选择的200%，默认打开app如图所示

![error](https://github.com/HMBSbige/NatTypeTester/assets/16422963/639f038b-0a30-43ff-8b18-db79ac6a6ce1)

App默认显示的尺寸非常小，字却很大。需要手动拉开尺寸匹配。是不是App窗口尺寸并没有理会系统的缩放比啊？一律按照100%显示的？这不太对吧？故反馈此BUG。

**Comment by HMBSbige** [comment]
😅这就是 WinUI3

之后还得 Avalonia 重写
