### ISSUE TITLE
能否加入以下测试域名？

### ISSUE THREAD

**Issue by srk24** [HMBSbige/NatTypeTester#241]
stun.l.google.com:19302
stun.nextcloud.com:443
global.stun.twilio.com
stun.cloudflare.com

**Comment by srk24** [comment]
> 首先，这四个域名全都不是用来测速 NAT 类型的
> 
> 其次可以自己加到 `stun.txt` 里，程序会自动加载

好的多谢。我看ipcheck这个项目用的这4个域名，所以都写出来了。

**Comment by HMBSbige** [comment]
能用来打洞的服务器不代表也能用来检测 NAT 类型
