### ISSUE TITLE
同样的Server两次测试结果不同

### ISSUE THREAD

**Issue by leogcry22** [HMBSbige/NatTypeTester#4]
使用的是最新版本，Server A第一次测试结果是PortRestrictedCone，再点一次就变成FullCone了，然后换Server B一样的先PortRestrictedCone，然后FullCone。换回Server A，无论怎么测都是FullCone了。。。有点迷惑。。

**Comment by HMBSbige** [comment]
很正常

**Comment by HMBSbige** [comment]
Use "RFC 5780"

**Comment by JWJUN233233** [comment]
可能是敏感防火墙
