### ISSUE TITLE
win10系统已安装.net 5.0 x86和x64版本，打开依然提示安装.net

### ISSUE THREAD

**Issue by jiuqianyuan** [HMBSbige/NatTypeTester#95]
win10系统已安装.net 5.0 x86和x64版本，打开依然提示安装.net

**Comment by jiuqianyuan** [comment]
另外,使用stun.syncthing.net、stun.bige0.com服务器检测NAT Type为Symmetric，使用stun.qq.com、stun.miwifi.com服务器则为FullCone，这是什么原因

**Comment by HMBSbige** [comment]
安装错了版本
https://aka.ms/dotnet/5.0/windowsdesktop-runtime-win-x64.exe
